name: CLI check and build
on:
  push:
    paths:
      - "cli/**"
      - ".github/workflows/cli.yaml"
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Test
        run: make test
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Test
        run: make build
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: code-letter-cli-${{ github.run_id }}
          path: ${{ github.workspace }}/out/code-letter-cli
          retention-days: 1
